# EpiMut - LOLA.jl
#
# Copyright (C) Chunyong Zhang
# Contact: Chunyong Zhang <zhangchunyong@tmu.edu.cn>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

using RCall,Getopt
function LOLA(diffcsv,pvaluecutoff,regiondb_path,name,outputfile)
R"""
    suppressMessages(library(LOLA))
    suppressMessages(library(GenomicRanges))
    library(ggplot2)
    a<-read.csv($diffcsv)
    b<-a[a$pval<$pvaluecutoff,]
    a1<-a[,c(1,2,3)]
    b1<-b[,c(1,2,3)]
    usersets=GRanges(seqnames =b1$chr,ranges=IRanges(start = b1$start,end=b1$end))
    useruniverse=GRanges(seqnames =a1$chr,ranges=IRanges(start = a1$start,end=a1$end))
    userdb=loadRegionDB($regiondb_path)
    loc=runLOLA(usersets,useruniverse,userdb)
    loc$filename<-gsub('.bed','',loc$filename)
    loc$filename<-factor(loc$filename,levels = loc$filename[order(loc$pValueLog)],ordered = T)
    ggplot(loc,aes(filename,pValueLog))+
        geom_bar(stat="identity",position = "dodge",width = 0.5,fill="#C9331CFF")+
        coord_flip()+theme_classic()+xlab("") + ylab("Enrichment score")
    ggsave(paste0($outputfile,'/',$name,'.pdf'))
    write.csv(loc,paste0($outputfile,'/',$name,'.LOLA.csv'))
"""
end
function Argparse()
    lst = Dict{String,String}()
    for (opt, arg) in getopt(ARGS, "hi:p:r:n:o:", ["help","inputfile=","pvaluecutoff=","regiondb_path=","name=","outputfile="])
        opt = replace(opt, "-" => "")
        arg = replace(arg, "=" => "")
        if opt == "help" || opt == "h"
            println("""
DESCRPTION      This program is for the locus overlap analysis (LOLA) after differential analysis.
                Make sure your R has installed LOLA, ggplot2 package.

USAGE           julia LOLA.jl [options] -i <inputfile> -p <pvaluecutoff> -r <regiondb_path> -n <outputname> -o <outputfile>

                    options
                    -h      --help              Show this message
                    -i      --inputfile         Input your differential analysis table, which was generated by DiffAnalysis.jl.
                    -p      --pvaluecutoff      Pvalue cutoff on enrichment tests to report. [Default: 0.05]
                    -r      --regiondb_path     Input regiondb_path (For more information, please visit https://databio.org/regiondb) for LOLA.
                    -n      --name              Input output name, stored as a pdf and csv format.
                    -o      --outputfile        Input output file path.

AUTHOR
                    Contact:     Chunyong Zhang; zhangchunyong@tmu.edu.cn
""")
        elseif opt == "inputfile" || opt == "i"
            lst["inputfile"] = arg
        elseif opt == "pvaluecutoff" || opt == "p"
            lst["pvaluecutoff"] = arg
        elseif opt == "regiondb_path" || opt == "r"
            lst["regiondb_path"] = arg
        elseif opt == "name" || opt == "n"
            lst["name"] = arg
        elseif opt == "outputfile" || opt == "o"
            lst["outputfile"] = arg
        else
            println("Please check your parameter!")
        end
    end
    lst
end

args = Argparse()
if length(args) > 1
    LOLA(args["inputfile"],parse(Float64,args["pvaluecutoff"]),args["regiondb_path"],args["name"],args["outputfile"])
end
