# EpiMut - VolcanoPlot.jl
#
# Copyright (C) Chunyong Zhang
# Contact: Chunyong Zhang <zhangchunyong@tmu.edu.cn>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

using RCall,Getopt
function volcanoplot(diffcsv,deltacutoff,pvaluecutoff,name,outputfile)
    R"""
    library(ggplot2)
    diff<-read.csv($diffcsv)
    diff$group<-as.factor(ifelse(diff$pval<$pvaluecutoff & abs(diff$delta_epimut_rate)>$deltacutoff,
                              ifelse(diff$delta_epimut_rate>$deltacutoff,'UP','DOWN'),'NOT'))
    this_title<-paste0('Cutoff for Delta EpiMut Rate is ',$deltacutoff,
                   '.\nThe number of up region is ',nrow(diff[diff$group=='UP',]),
                   '.\nThe number of down region is ',nrow(diff[diff$group=='DOWN',]),'.')
    g<-ggplot(data = diff,aes(x=delta_epimut_rate,y=-log10(pval),color=group))
    pdf(paste0($outputfile,'/',$name,'.pdf'),width=10,height = 6)
    final<-g+geom_point(alpha=0.6,size=2)+theme_classic()+
      xlab('Delta EpiMut Rate')+ylab('-log10 Pval')+
      ggtitle(this_title)+theme(plot.title = element_text(size = 15,hjust = 0.5))+
      scale_color_manual(values = c('#4DBBD5FF','#CCCCCCFF','#E64B35FF'))+
      geom_hline(yintercept=-log10($pvaluecutoff),linetype=2)+
      geom_vline(xintercept=c(-$deltacutoff,$deltacutoff),linetype=2)
    print(final)
    dev.off()
    """
end
function Argparse()
    lst = Dict{String,String}()
    for (opt, arg) in getopt(ARGS, "hi:d:p:n:o:", ["help","inputfile=","deltacutoff=","pvaluecutoff=","name=","outputfile="])
        opt = replace(opt, "-" => "")
        arg = replace(arg, "=" => "")
        if opt == "help" || opt == "h"
            println("""
DESCRPTION      This program is for drawing volcano plot after differential analysis.

USAGE           julia VolcanoPlot.jl [options] -i <inputfile> -n <outputname> -o <outputfile>

                    options
                    -h      --help              Show this message
                    -i      --inputfile         Input your diffrential analysis table, which was generated by DiffAnalysis.jl.
                    -d      --deltacutoff       EpiMut rate difference cutoff between the two groups (group1 minus group2). [Default: 0.2]
                    -p      --pvaluecutoff      Pvalue cutoff on enrichment tests to report. [Default: 0.05]
                    -n      --name              Input output name, stored as a pdf format.
                    -o      --outputfile        Input output file path.

AUTHOR
                    Contact:     Chunyong Zhang; zhangchunyong@tmu.edu.cn
""")
        elseif opt == "inputfile" || opt == "i"
            lst["inputfile"] = arg
        elseif opt == "deltacutoff" || opt == "d"
            lst["deltacutoff"] = arg
        elseif opt == "pvaluecutoff" || opt == "p"
            lst["pvaluecutoff"] = arg
        elseif opt == "name" || opt == "n"
            lst["name"] = arg
        elseif opt == "outputfile" || opt == "o"
            lst["outputfile"] = arg
        else
            println("Please check your parameter!")
        end
    end
    lst
end
function default(args,c)
    if isequal(c,"deltacutoff") && isequal(getkey(args,c,"no"),"no")
        args[c]="0.2"
    elseif isequal(c,"pvaluecutoff") && isequal(getkey(args,c,"no"),"no")
        args[c]="0.05"
    else
        args
    end
end
args = Argparse()
if length(args) > 1
    default(args,"deltacutoff");default(args,"pvaluecutoff")
    volcanoplot(args["inputfile"],parse(Float64,args["deltacutoff"]), parse(Float64,args["pvaluecutoff"]),args["name"],args["outputfile"])
end
